defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:22.10

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - run:
          name: Test
          command: npm t
      - run:
          name: Check code syntax
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install published
          command: npx published --git-tag
  page:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Remove things that bother parcel
          command: "sed -i '/\"main\": \"index.js\",/d' ./package.json"
      - run:
          name: Build static playground
          command: npm run build
      - run:
          name: Copy circleci config
          command: cp -r .circleci playground/dist/
      - run:
          name: Post to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s playground/dist/.

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - test:
        filters:
          branches:
            ignore:
              - gh-pages
      - publish:
          context: org-global
          requires:
            - test
      - page:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
