defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:lts
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    parameters:
      image:
        description: Docker image
        default: "cimg/node:lts"
        type: string
    <<: *defaults
    docker:
      - image: "<<parameters.image>>"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm t
      - run: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo -e $NPMRC > ~/.npmrc
      - run: npx published --git-tag
  page:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Remove things that bother parcel
          command: "sed -i '/\"main\": \"index.js\",/d' ./package.json"
      - run:
          name: Build static playground
          command: npm run build
      - run:
          name: Copy circleci config
          command: cp -r .circleci playground/dist/
      - run:
          name: Post to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s playground/dist/.

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - install:
          context: org-global
      - test:
          requires:
            - install
          context: org-global
          filters:
            branches:
              ignore:
                - gh-pages
          matrix:
            parameters:
              image:
                - "cimg/node:14.21"
                - "cimg/node:16.20"
                - "cimg/node:18.17"
                - "cimg/node:20.5"
      - publish:
          context: org-global
          requires:
            - test
      - page:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
